version: "3.9"
services:
  mysql:
    image: "mysql:latest"
    container_name: mysqlContainer
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
    ports:
      - "3306:3306"
    volumes:
      - ./commands.sql:/commands.sql:rwx

networks:
  default:
    name: myNetwork
